import { Geist, Geist_Mono } from "next/font/google";
import "./globals.css";
<<<<<<< HEAD
import Nav from "../components/navBar/Nav";
import Footer from "../components/footer/Footer";

const geistSans = Geist({
  variable: "--font-geist-sans",
  subsets: ["latin"],
});

const geistMono = Geist_Mono({
  variable: "--font-geist-mono",
  subsets: ["latin"],
});

export const metadata = {
  title: "PDFix",
  description: "Crie currículos profissionais rapidamente",
};

export default function RootLayout({ children }) {
  return (
    <html lang="pt-BR">
      <body className={`${geistSans.variable} ${geistMono.variable} antialiased`}>
        <div className="min-h-screen bg-white text-zinc-800">
          <Nav />
          <main>{children}</main>
          <Footer />
        </div>
      </body>
    </html>
  );
}

=======
import { jsx as _jsx } from "react/jsx-runtime";
const geistSans = Geist({
  variable: "--font-geist-sans",
  subsets: ["latin"]
});
const geistMono = Geist_Mono({
  variable: "--font-geist-mono",
  subsets: ["latin"]
});
export const metadata = {
<<<<<<<< HEAD:frontend/src/app/layout.js
  title: "Create Next App",
  description: "Generated by create next app"
========
  title: "PDFix",
  description: "Seu Web APP de geração de currículos",
>>>>>>>> origin/develop:frontend/src/app/layout.jsx
};
export default function RootLayout({
  children
}) {
  return /*#__PURE__*/_jsx("html", {
    lang: "en",
    children: /*#__PURE__*/_jsx("body", {
      className: `${geistSans.variable} ${geistMono.variable} antialiased`,
      children: children
    })
  });
}
>>>>>>> origin/develop
