import { Geist, Geist_Mono } from "next/font/google";
import "./globals.css";
import { jsx as _jsx } from "react/jsx-runtime";
const geistSans = Geist({
  variable: "--font-geist-sans",
  subsets: ["latin"]
});
const geistMono = Geist_Mono({
  variable: "--font-geist-mono",
  subsets: ["latin"]
});
export const metadata = {
  title: "Create Next App",
  description: "Generated by create next app"
};
export default function RootLayout({
  children
}) {
  return /*#__PURE__*/_jsx("html", {
    lang: "en",
    children: /*#__PURE__*/_jsx("body", {
      className: `${geistSans.variable} ${geistMono.variable} antialiased`,
      children: children
    })
  });
}